spring:
  application:
    name: demo
  jpa:
    database: POSTGRESQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          # 配置开启自动更新表结构
          auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:root}?characterEncoding=UTF-8&stringtype=unspecified
    druid:
      max-active: 5 #最大连接池数量
      min-idle: 2 #最小连接池数量
      max-wait: 1000 #获取连接最大等待时间
      min-evictable-idle-time-millis: 300000 #空闲连接存活时间
      keep-alive: true
      keep-alive-between-time-millis: 300000 #keep-alive操作时间间隔
      pool-prepared-statements: false #是否缓存prepareStatement, 官方建议MySQL下建议关闭
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: true #申请连接时检查连接是否有效
      test-on-return: false #归还连接时检查连接是否有效
      test-while-idle: true #连接空闲时检查是否有效
      time-between-eviction-runs-millis: 60000 #连接检查时间间隔
      use-unfair-lock: true #使用非公平锁
      validation-query: null # 数据库检活sql
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计, wall用于防火墙, log4j2为你自己使用的日志，如果是log4j就写log4j,我这里用的log4j2
      filters: stat,wall,log4j2
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
        wall:
          config:
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: 192.168.1.100